### ISSUE TITLE
add A4 or A5 blink in final version of code for pogobed verification 

### ISSUE THREAD

**Issue by JoelEB** [JoelEB/ApoBoard2017#1]
add A4 or A5 blink in final version of code for pogobed verification when programming

**Comment by spec7er** [comment]
what code is watching A4/A5?? or is it an LED?  How should it blink? Continuously? Blink once?

**Comment by JoelEB** [comment]
I can add this, but I just have a regular LED attached to pin A5 that will blink a few times in setup() to verify the code made it on. But I also added an addressable LED, so we could just use that to see if if starts blinking (each will be random, since the animations will be randomized).

**Comment by JoelEB** [comment]
Added 5/28
